### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by vittorezhang** [tangbing/github_client#1]
输入正确的用户名和密码后，提示用户名或密码不正确。

**Comment by tangbing** [comment]
要有自己的github账号，用户名是github 用户名，密码是github token，参考以下链接[https://zhuanlan.zhihu.com/p/393441709配置](https://zhuanlan.zhihu.com/p/393441709%E9%85%8D%E7%BD%AE)

**Comment by vittorezhang** [comment]
> 要有自己的github账号，用户名是github 用户名，密码是github token，参考以下链接[https://zhuanlan.zhihu.com/p/393441709配置](https://zhuanlan.zhihu.com/p/393441709%E9%85%8D%E7%BD%AE)

可以登录了，谢谢
